[connections.my_example_connection]
account = "EPWWRIF-XUB38589"
user = "BRIANANBLICKS"
password = "SnowflakeLearning9!"
authenticator = "externalbrowser"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"